language: java
install:
  - git clone https://github.com/rappid/webtest.git /tmp/webtest && mvn -f /tmp/webtest/pom.xml clean install
before_script:
  - chmod +x bin/sauce_connect_setup.sh && bin/sauce_connect_setup.sh
  - echo "Username: $SAUCE_USERNAME"
script:
  - "mvn -f test/pom.xml clean integration-test -Dbrowser=chrome -Dgrid.port=4445 -DthreadCount=1 -DstartUrl=http://preview.rappidjs.com"
env:
  global:
   - secure: "cxsEJPxHP0GO0bnE4BstzdORy95PcTBXs1alzZ5v4bpukdnhQ8oUAV+db8TwQhTYdQ7oUXVrlVBpufeDsYM5gLhIljIPEDpRQomZf8s+0tJjX8kqR6R0MaTvx5cWHvJmM7v9KM9ClkxdQv1u9Dm8eZ78P2qXdS3jkXSpJsaRjoA="
   - secure: "PlfgG5vWIcEb+yRXo8FsBPKmiw/uII/CofKTY0yvtuoqEXbTstn5YVkBGUrJynrPYhowdkwITMTPPJml1KR9UaVnKJB3EVW8jPB9RbnZrx0EMFZsa4VDxyvPLflSvoA1ueTryMLcyoxr205wVz12b+tt2xwkfqkjCxhTMfQuRfE="
branches:
 only:
   - dev
notifications:
  email:
    - tony@rappidjs.com
    - marcus@rappidjs.com